### ISSUE TITLE
add `tf_interpolate` for changing arg-grid of tf objects

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tidyfun#107]
see discussion #104 -- syntactic sugar for `tf<d|b>(<tf>, arg = <new grid>)`.

**Comment by fabian-s** [comment]
@jeff-goldsmith  IIUC the use case for this is to get all functions in a tf object onto a new and common grid - right?

This is very straightforward for tfb and regular tfd.

I'm unsure about how to implement this so that we have a good tradeoff between convenience and safety for irregular data with unequal start or end points--
we can currently do something like this (from ?tfd.tf):
```r
(f <- c(dti_df$cca[1], dti_df$rcst[2]))
#> tfd[2] on (0,1) based on 43 to 93 (mean: 68) evaluations each
#> inter-/extrapolation by tf_approx_linear 
#> 1001_1: (0.000,0.49);(0.011,0.52);(0.022,0.54); ...
#> 1002_1: ( 0.22,0.44);( 0.24,0.48);( 0.26,0.48); ...
#does not yield regular data because linear extrapolation yields NAs outside observed range:
tfd(f, arg = seq(0, 1, l = 101)) 
#> Warning in tfd.tf(f, arg = seq(0, 1, l = 101)): 23 evaluations were NA,
#> returning irregular tfd.
#> tfd[2] on (0,1) based on 78 to 101 (mean: 90) evaluations each
#> inter-/extrapolation by tf_approx_linear 
#> 1001_1: (0.00,0.49);(0.01,0.51);(0.02,0.53); ...
#> 1002_1: (0.23,0.46);(0.24,0.48);(0.25,0.48); ...
# this "works" (but may not yield sensible values..!!) for e.g. constant extrapolation:
tfd(f, evaluator = tf_approx_fill_extend, arg = seq(0, 1, l = 101))
#> tfd[2] on (0,1) based on 101 evaluations each
#> interpolation by tf_approx_fill_extend 
#> 1001_1: (0.00,0.49);(0.01,0.50);(0.02,0.53); ...
#> 1002_1: (0.00,0.44);(0.01,0.44);(0.02,0.44); ...
plot(f, col = 2)
lines(tfd(f, evaluator = tf_approx_fill_extend, arg = seq(0, 1, l = 151)))
```

![](https://i.imgur.com/StMJJ4M.png)

Of course, we can define `tf_interpolate(f, arg)` as equivalent to `tfd(f, arg = arg)` or  `tfb(f, arg = arg)` but then it's not useful for the subset of cases where it *could* be most useful, i.e. irregular data. 

Options that I can think of (mutually exclusive, I think):

1. it's the users' problem. `tf_interpolate` gets an `evaluator`-arg, if they want to extrapolate, they can use/define an evaluator that does that. `tf_interpolate` does not reliably turn irregular data into regular data. life is hard. suffering ennobles the spirit.
2. `tf_interpolate` has a `force` arg. If that's set to TRUE,  it never yields irregular returns. Instead, if the `evaluator`of the input returns NAs for some of the new `arg` values, we then do last value carried forward or next value carried backwards to fill them up with numbers. (this will often yield nonsense, see example). `tf_interpolate` always turns irregular data into regular data.
2. `tf_interpolate` has a `overlap` arg. If that's set to TRUE,  it never yields irregular returns.  Instead, the new `arg`-vector is truncated so that its start [end] point is larger [smaller] than the min [max] of the observed first [last] arg-values of the input. we only interpolate over the range that all functions have in common. If the data are very irregular, this can yield a new `tf` defined on a much smaller domain. `tf_interpolate` always turns irregular data into regular data.

thoughts?

**Comment by jeff-goldsmith** [comment]
I stumbled across the issue in #104 when I was looking through / update the [Vectors and Operations vignette](https://tidyfun.github.io/tidyfun/articles/x01_tf_Vectors.html), rather than through an actual use case. So ... it may be worth doing something easy for now, and if we really truly run into a problem we can revisit. 

The use case I could come up most easily would be downsampling a really densely observed grid to work with a more manageable dataset in (preliminary?) analyses. In that case, sparse and irregular wouldn't be an issue. 

I have a harder time imaging the use of `tf_interpolate` to get irregular data over an even grid, especially if that involves extrapolating -- really there should be some model / FPCA involved there, and then defining the grid is a part of that analysis. 

All things considered, I like option 1 -- users would get functions evaluated at the gridpoints they want, but only where it's possible to interpolate between existing values. A warning message that says "maybe do FPCA" in addition to "suffering ennobles the spirit" would acknowledge the issues and point users in a reasonable direction.

**Comment by fabian-s** [comment]
You are a fount of wisdom and maturity. I cherish our collaboration. This is the way.

**Comment by jeff-goldsmith** [comment]
This is the way.
