### ISSUE TITLE
rename `as.data.frame`

### ISSUE THREAD

**Issue by jeff-goldsmith** [tidyfun/tidyfun#113]
right now, calling `as.data.frame()` on a `tf` vector produces a long-format dataframe (columns for id, arg, value). but if you call `tibble()` on a `tf` vector, it creates a dataframe with a `tf`-column, which is maybe more what one would expect. it'd also be nice if these functions had basically the same behavior.

should we rename `as.data.frame` to .. `as_long_df`? i don't have a good replacement name tbh

**Comment by fabian-s** [comment]
agree, good point  -- tibble(tf), data.frame(tf)  and as.data.frame(tf) should all give the same result, and the least surprising result would be a one-column data.frame containing tf. 

could rename the function that turns a tf into a long dataframe **pivot_longer()**, since the functionality is exactly whatthe dplyr-function of that name does. just need to define a S3-method for dplyr's generic.

**Comment by jeff-goldsmith** [comment]
what about `tf_unnest()`? right now that works to expand a dataframe containing a functional observation. would it be too weird for that to work on a tf vector, too?

**Comment by fabian-s** [comment]
even better, yeah. 
i'll turn `tf_unnest` into a generic with methods for dataframe and tf. excellent!
