### ISSUE TITLE
fix nest/unnest for tidyr >= 1.0.0

### ISSUE THREAD

**Issue by fabian-s** [tidyfun/tidyfun#83]
They broke the fucking interface. I hate them.

**Comment by fabian-s** [comment]
do revert https://github.com/tidyfun/tidyfun/commit/85083c903844d9109e1d40cbff99e5fa5ddf09d2 before closing this

**Comment by jeff-goldsmith** [comment]
I dunno if this is related, but `tf_nest` was broken -- 2e937be21545d0751b1a9b38da4e032f91ef6279 addresses an issue that seems to come from using `pmap` and `select`. I guess you have to !! things being passed into `select` now?

**Comment by jeff-goldsmith** [comment]
1bd38c9f8bec1bff892f0e598cc568701f583df2 broke ``gglasagna`` ... sorry.

the issue seems to be that `gglasagna` expects `tf_unnest` to produce an `id` column, which it no longer does. i think we have two options:

- easy -- require `id` as an input, and ask users to provide it. 
- slightly harder -- check to see if a unique `id` column exists in the data or if the `tf` vector to be plotted has an id we can extract (and i guess maybe do some kinda checks if both exist), and if not create one

happy to work on this, just want to see if others have thoughts on the best solution

**Comment by fabian-s** [comment]
thx @jeff-goldsmith. should be ok now.
