### ISSUE TITLE
Wavelets: irregular spaced input

### ISSUE THREAD

**Issue by SvenLorenz** [tidyfun/tidyfun#89]
Input datasets are not always evenly spaced and since common wavelet implementations are dependant on that this issue arrises.

Current best solution is `makegrid()` and `irregwd()` from `wavethresh`.
```r
x <- c(.01, .02, .05, 0.1, .11, .5, .51, .7)
y <- c(1,1,7,9,2,8,8,6)
irreggrid <- makegrid(x, y)
irregtest <- irregwd(irreggrid)
```
The problem with `makegrid` is that it only takes inputs between 0 and 1 for x, then spaces them out evenly and lastly linearly interpolates y. We might not want to linearly interpolate.

**Comment by fabian-s** [comment]
Thoughts:
Best strategy seems to me to depend on *how far* the grid is from being evenly spaced (and dyadic, that aspect has to be considered here as well!) 

1. if only minor adjustments are needed to get to a regular dyadic grid, interpolation onto a regular grid will work well enough. 
2. I worry about the effect of interpolation in cases where the grid is dense in some part and sparse in others -- a regular grid will then systematically put fewer pseudo-data points where the actually observed data lies, and systematically more pseudo-data points where there's less of it.... this would be much less of a problem if we could estimate wavelet coefficients with weights on the data that depend on how far they are from actually observed points. This would be easy-ish to do if wavelet coefficients were determined by weighted LS fits with the wavelet basis matrix instead of the pyramid algorithm used in `wavethresh::wd`.
3. open question to me under which circumstances you'd want to do interploation to a dyadic regular grid directly or combine interpolation of the data with some kind of "signal extension" / "padding" strategy IFF the original grids are far from having a dyadic number
4. final complication: whichever strategy is implemented should be feasible for *vectors* of functions that may have been observed on *different* irregular grids with *different* number of obs.
